apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: api-pipeline
  namespace: tekton-pipelines
spec:
  resources:
    - name: git-repo
      type: git
    - name: image-registry
      type: image
  params:
    - name: pathToDockerFile
      type: string
    - name: pathToContext
      type: string
    - name: appChartRepo
      type: string
    - name: appName
      type: string
    - name: imageRepository
      type: string
    - name: ingressHost
      type: string
    - name: pvcName
      type: string
    - name: pvcResourcesStorage
      type: string
    - name: pvcStorageClassName
      type: string
    - name: backendAppEnv
      type: string
    - name: backendConsumerKey
      type: string
    - name: backendConsumerSecret
      type: string
    - name: backendAccessToken
      type: string
    - name: backendAccessTokenSecret
      type: string
    - name: backendAuthToken
      type: string
  tasks:
    - name: build-and-deploy
      taskRef:
        name: build-and-deploy
      params:
        - name: pathToDockerFile
          value: "$(params.pathToDockerFile)"
        - name: pathToContext
          value: "$(params.pathToContext)"
        - name: appChartRepo
          value: "$(params.appChartRepo)"
        - name: appName
          value: "$(params.appName)"
        - name: imageRepository
          value: "$(params.imageRepository)"
        - name: ingressHost
          value: "$(params.ingressHost)"
        - name: pvcName
          value: "$(params.pvcName)"
        - name: pvcResourcesStorage
          value: "$(params.pvcResourcesStorage)"
        - name: pvcStorageClassName
          value: "$(params.pvcStorageClassName)"
        - name: backendAppEnv
          value: "$(params.backendAppEnv)"
        - name: backendConsumerKey
          value: "$(params.backendConsumerKey)"
        - name: backendConsumerSecret
          value: "$(params.backendConsumerSecret)"
        - name: backendAccessToken
          value: "$(params.backendAccessToken)"
        - name: backendAccessTokenSecret
          value: "$(params.backendAccessTokenSecret)"
        - name: backendAuthToken
          value: "$(params.backendAuthToken)"
      resources:
        inputs:
          - name: git-repo
            resource: git-repo
        outputs:
          - name: image-registry
            resource: image-registry
